SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ak_Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NULL,
	[Active] [tinyint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ak_Users] ADD  CONSTRAINT [PK_ak_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ak_Users] ADD  CONSTRAINT [DEFAULT_ak_Users_Active]  DEFAULT ((0)) FOR [Active]
GO
